name: Build Status

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - 'jruby-9.1.17.0'
        gemfile:
          - lowest
          - latest
        exclude:
          # Ruby > 2.6 removed BigDecimal.new which was used on Rails 4.1 (removed with Rails 4.2 though)
          - ruby: '2.7'
            gemfile: lowest
          - ruby: '3.0'
            gemfile: lowest
          - ruby: '3.1'
            gemfile: lowest
          - ruby: '3.2'
            gemfile: lowest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bundler 1.x for Rails 4.x
        if: ${{ matrix.gemfile == 'lowest' }}
        run: echo "BUNDLER_VERSION=1.17.3" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}
      - run: ruby --version
      - name: Run specs
        run: bundle exec rspec
      - name: Publish code coverage
        if: ${{ matrix.ruby == '3.1' && matrix.gemfile == 'latest' }} # only one is needed!
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          debug: true
          verifyDownload: true
